'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import ErrorDialog from './ErrorDialog';
import {useLanguage,LanguageSwitcher} from './Language';
import {cookieLanguage,resolveLanguage} from '../lib/i18n.mjs';
import {ArrowLeft,ArrowUpRight,CheckCircle2,Download,Globe2,LoaderCircle,LogOut,RefreshCw} from 'lucide-react';

const labels={pending:'等待管理员处理',processing:'翻译处理中',ready:'可发布',published:'已公开',failed:'需要重试',split:'已拆分 · 历史记录'};
const canSplit=article=>!!article&&['pending','processing','ready','failed'].includes(article.status)&&article.originals.length>1&&article.originals.length<=20;
const splitSignature=article=>JSON.stringify([article?.id,article?.status,article?.lease,article?.originals.map(image=>[image.id,image.position])]);
async function api(route,options={}){
 const response=await fetch('/api/'+route,{...options,headers:{'X-Hooboo-Language':resolveLanguage(cookieLanguage(document.cookie),navigator.language),...options.headers},cache:'no-store'});
 const body=await response.json();
 if(!response.ok)throw Object.assign(new Error(body.error_key||body.error||'操作失败，请重试。'),{status:response.status});
 return body;
}
export default function Admin(){
 const {t,imageCount}=useLanguage();
 const [user,setUser]=useState(null),[loaded,setLoaded]=useState(false),[articles,setArticles]=useState([]),[active,setActive]=useState(null);
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[outputs,setOutputs]=useState({}),[reviewed,setReviewed]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [splitTarget,setSplitTarget]=useState(null),[splitting,setSplitting]=useState(false);
 const outputRef=useRef({}),claimKey=useRef(null),splitRequest=useRef(null),selectedArticle=useRef(null),selectionVersion=useRef(0),refreshVersion=useRef(0),mounted=useRef(true);
 const splitButton=useRef(null),cancelSplitButton=useRef(null),detailHeading=useRef(null);
 async function refresh(id){const version=++refreshVersion.current,selection=selectionVersion.current;const result=await api('admin/submissions');if(mounted.current&&version===refreshVersion.current){setArticles(result.articles);if(id&&selectedArticle.current?.id===id&&selection===selectionVersion.current){const next=result.articles.find(a=>a.id===id)||null;selectedArticle.current=next;setActive(next);setSplitTarget(null);}}return result.articles;}
 useEffect(()=>{mounted.current=true;function beforeUnload(event){if(!splitRequest.current)return;event.preventDefault();event.returnValue='';}window.addEventListener('beforeunload',beforeUnload);return()=>{mounted.current=false;window.removeEventListener('beforeunload',beforeUnload);};},[]);
 useEffect(()=>{if(splitTarget)cancelSplitButton.current?.focus();},[splitTarget]);
 useEffect(()=>{let disposed=false;async function boot(){try{const result=await api('session');if(disposed)return;if(!result.user){window.location.replace('/login');return;}if(result.user.role!=='admin'){setError(t("此页面仅限管理员使用。"));return;}setUser(result.user);const list=await api('admin/submissions');if(!disposed)setArticles(list.articles);}catch(e){if(!disposed)setError(e.message);}finally{if(!disposed)setLoaded(true);}}boot();return()=>{disposed=true;};},[]);
 useEffect(()=>()=>Object.values(outputRef.current).forEach(output=>URL.revokeObjectURL(output.url)),[]);
 const activeId=active?.id,activeLease=active?.status==='processing'?active.lease:null,csrf=user?.csrf;
 useEffect(()=>{if(!activeId||!activeLease||!csrf)return;const timer=setInterval(async()=>{if(splitRequest.current)return;try{await api('worker/articles/'+activeId+'/heartbeat',{method:'POST',headers:{'X-CSRF-Token':csrf,'X-Job-Lease':activeLease}});}catch(e){if(mounted.current&&!splitRequest.current&&selectedArticle.current?.id===activeId&&selectedArticle.current?.status==='processing')setError(t("续期失败：")+e.message);}},600000);return()=>clearInterval(timer);},[activeId,activeLease,csrf]);
 function clearOutputs(){Object.values(outputRef.current).forEach(output=>URL.revokeObjectURL(output.url));outputRef.current={};setOutputs({});}
 function loadArticle(article){selectionVersion.current++;selectedArticle.current=article;clearOutputs();setActive(article);setTitle(article?.title_en||'');setBody(article?.text_en||'');setReviewed(false);setSplitTarget(null);setError('');setNotice('');}
 function choose(article){if(splitRequest.current)return;loadArticle(article);}
 function openRelated(id){if(busy||splitRequest.current)return;const article=articles.find(item=>item.id===id);if(article){choose(article);requestAnimationFrame(()=>{detailHeading.current?.focus();detailHeading.current?.scrollIntoView({block:'start'});});}else setError(t("请刷新投稿列表后查看关联文章。"));}
 function guardNavigation(event){if(splitRequest.current)event.preventDefault();}
 function beginSplit(){if(busy||splitRequest.current||!canSplit(active))return;setSplitTarget(active);setNotice('');}
 function cancelSplit(){if(splitRequest.current)return;setSplitTarget(null);requestAnimationFrame(()=>splitButton.current?.focus());}
 async function confirmSplit(){
  if(busy||splitRequest.current||!splitTarget)return;
  const target=splitTarget;
  if(!canSplit(selectedArticle.current)||splitSignature(selectedArticle.current)!==splitSignature(target)){setSplitTarget(null);setError(t("投稿已更新，请重新检查后再拆分。"));return;}
  splitRequest.current=target.id;refreshVersion.current++;setBusy(true);setSplitting(true);setError('');setNotice('');
  try{
   const result=await mutate('admin/submissions/'+target.id+'/split',undefined,target.lease);
   if(!mounted.current)return;
   claimKey.current=null;
   const children=result.children,history={...target,status:'split',lease:null,split:{children:children.map(child=>({id:child.id,title_cn:child.title_cn,status:child.status,source_asset_id:child.provenance?.source_asset_id,source_position:child.provenance?.source_position}))}};
   setArticles(previous=>[...previous.filter(article=>article.id!==target.id&&!children.some(child=>child.id===article.id)),history,...children]);
   loadArticle(children[0]||history);
   setNotice(t(result.already_split?"这份投稿已拆分，已打开现有的独立文章。":"拆分完成。已打开第一篇独立文章，请逐篇领取、翻译并检查。"));
   try{await refresh(children[0]?.id||target.id);}catch(e){if(mounted.current)setError(t("拆分已完成，但列表刷新失败。请刷新投稿列表。"));}
   if(mounted.current)requestAnimationFrame(()=>detailHeading.current?.focus());
  }catch(e){if(mounted.current){setSplitTarget(null);setError(e.message);try{await refresh(target.id);}catch{ /* Keep the original failure visible; a fresh explicit request is safe to retry. */ }}}
  finally{splitRequest.current=null;if(mounted.current){setBusy(false);setSplitting(false);}}
 }
 function selectOutput(position,file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>12*1024*1024){setError(t("请上传小于 12 MB 的 JPG、PNG 或 WebP 英文图片。"));return;}const previous=outputRef.current[position];if(previous)URL.revokeObjectURL(previous.url);const next={...outputRef.current,[position]:{file,url:URL.createObjectURL(file)}};outputRef.current=next;setOutputs(next);setReviewed(false);setError('');}
 async function mutate(route,data,lease,method='POST'){
  const headers={'X-CSRF-Token':user.csrf};if(lease)headers['X-Job-Lease']=lease;
  let content=data;if(data&&!(data instanceof FormData)){headers['Content-Type']='application/json';content=JSON.stringify(data);}
  return api(route,{method,headers,body:content});
 }
 async function claim(){if(splitRequest.current)return;setBusy(true);setError('');setNotice('');claimKey.current ||= crypto.randomUUID();try{const result=await api('worker/claim',{method:'POST',headers:{'X-CSRF-Token':user.csrf,'Idempotency-Key':claimKey.current}});claimKey.current=null;await refresh();if(result.submission){choose(result.submission);setNotice(t("已领取原稿。请下载并翻译，完成后上传英文图片。"));}else setNotice(t("当前没有可领取的投稿。已领取的任务可从列表继续处理。"));}catch(e){if(e.status===409)claimKey.current=null;setError(e.message);}finally{setBusy(false);}}
 async function save(){if(splitRequest.current)return;if(!reviewed){setError(t("请检查英文文字和图片版式后勾选确认。"));return;}setBusy(true);setError('');setNotice('');try{const lease=active.lease;if(!lease)throw Error(t("任务未领取或已过期，请刷新后重新领取。"));for(const original of active.originals){const output=outputs[original.position];if(!output&&!active.images.some(image=>image.position===original.position))throw Error(t("请上传第 ")+(original.position+1)+t(" 张英文图片。"));if(output){const form=new FormData();form.set('image',output.file);await mutate('worker/articles/'+active.id+'/images/'+original.position,form,lease,'PUT');}}await mutate('worker/articles/'+active.id+'/complete',{title_en:title,text_en:body},lease);await refresh(active.id);clearOutputs();setNotice(t("英文版本已保存，可以直接发布。"));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function publish(){if(splitRequest.current)return;setBusy(true);setError('');try{const result=await mutate('worker/articles/'+active.id+'/publish');await refresh(active.id);setNotice(t("发布成功。公开地址：")+result.url);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function retry(){if(splitRequest.current)return;setBusy(true);setError('');try{await mutate('admin/submissions/'+active.id+'/retry');const list=await refresh();choose(list.find(a=>a.id===active.id));setNotice(t("已重新加入处理队列，请领取下一篇。"));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function logout(){if(splitRequest.current)return;try{await mutate('logout');window.location.href='/login';}catch(e){setError(e.message);}}
 const processing=active?.status==='processing'&&!!active.lease;
 return <><ErrorDialog message={error} onDismiss={()=>setError('')}/><header className="header"><Link className="brand" href="/" onNavigate={guardNavigation} aria-disabled={splitting}><span className="brand-symbol">{t("译")}</span><span>{t("图译")}<small>hooboo</small></span></Link><nav className="admin-nav" aria-label={t("管理导航")}><Link href="/" onNavigate={guardNavigation} aria-disabled={splitting}>{t("公开作品集")} <ArrowUpRight size={15}/></Link>{user&&<button className="icon-button" onClick={logout} disabled={busy} aria-label={t("退出登录")}><LogOut size={18}/></button>}</nav><LanguageSwitcher/></header>
 <main className="dashboard admin-workspace"><div className="workspace-top"><div><div className="eyebrow muted">{t("授权翻译与发布")}</div><h1>{t("管理员工作台")}<span className="welcome">{user?.username}</span></h1><p className="subtle">{t("下载原稿，保留版式制作英文图片，检查后直接公开。")}</p></div>{user&&<button className="button primary" onClick={claim} disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Download size={18}/>}{t("领取下一篇")}</button>}</div>
 <div className="workflow"><span><b>01</b> {t("领取并下载")}</span><span><b>02</b> {t("上传英文版本")}</span><span><b>03</b> {t("检查并发布")}</span></div>
 {splitting&&<div role="status" className="alert"><LoaderCircle className="spin" size={18}/>{t("正在拆分，请等待保存完成后再离开。")}</div>}
 {notice&&<div role="status" className="alert success"><CheckCircle2 size={18}/>{t(notice)}</div>}
 {!loaded?<div className="loading"><LoaderCircle className="spin"/>{t("正在加载…")}</div>:user&&<div className="admin-grid"><aside className="submissions-panel"><div className="panel-heading"><h2>{t("全部投稿")} <span className="count">{articles.length}</span></h2><button className="icon-button" disabled={busy} onClick={()=>refresh(active?.id).catch(e=>setError(e.message))} aria-label={t("刷新投稿")}><RefreshCw size={18}/></button></div>{!articles.length&&<p className="subtle">{t("暂时没有投稿。")}</p>}{articles.map(article=><button type="button" className={'admin-job '+(active?.id===article.id?'selected':'')} key={article.id} disabled={busy} onClick={()=>choose(article)}><span className={'status '+article.status}>{t(labels[article.status]||article.status)}</span><strong>{article.title_cn}</strong><small>{article.contributor} · {imageCount(article.originals.length)}</small></button>)}</aside>
 <section className="upload-panel">{!active?<div className="empty"><Globe2 size={30}/><h3>{t("选择投稿或领取下一篇")}</h3><p>{t("原稿和未发布的英文图片仅对授权账号可见。")}</p></div>:<><div className="panel-heading"><div><span className={'status '+active.status}>{t(labels[active.status]||active.status)}</span><h2 ref={detailHeading} tabIndex={-1}>{active.title_cn}</h2><p className="subtle">{t("投稿编号：")}{active.id}</p></div>{active.status==='published'&&<Link className="text-link" href={'/article/'+active.id} onNavigate={guardNavigation} aria-disabled={splitting}>{t("查看公开文章")} <ArrowUpRight size={16}/></Link>}</div>
 {active.text_cn&&<details className="optional" open><summary>{t("中文正文")}</summary><p className="admin-source-text">{active.text_cn}</p></details>}{active.source&&<p className="subtle">{t("来源：")}<a href={active.source} target="_blank" rel="noreferrer">{active.source}</a></p>}{active.credit&&<p className="subtle">{t("作者：")}{active.credit}</p>}{active.error&&<div className="alert error">{active.error}</div>}
 {active.provenance&&<aside className="admin-lineage" aria-label={t("拆分来源")}><h3>{t("拆分来源")}</h3><p>{t("原投稿：")}<button type="button" className="text-link" disabled={busy} onClick={()=>openRelated(active.provenance.parent_id)}>{active.provenance.parent_title_cn||active.provenance.parent_id}</button></p><p className="subtle">{t("原稿图片序号：")}{active.provenance.source_position+1}</p><p className="subtle">{t("中文标题为临时编号。请先查看这张图片，再拟定对应的英文标题并逐张翻译、检查。")}</p>{active.provenance.parent_text_cn&&<details className="optional"><summary>{t("原投稿中文正文（仅供参考）")}</summary><p className="admin-source-text">{active.provenance.parent_text_cn}</p></details>}</aside>}
 {active.status==='split'&&<aside className="admin-lineage" aria-label={t("拆分后的文章")}><h3>{t("拆分后的文章")}</h3><p className="subtle">{t("原投稿仅保留为私密历史记录，不能再领取、重试或发布。原稿和已有英文草稿保留在此。")}</p><ul className="split-children">{active.split?.children.map(child=><li key={child.id}><button type="button" className="text-link" disabled={busy} onClick={()=>openRelated(child.id)}>{child.title_cn}</button><span className={'status '+child.status}>{t(labels[child.status]||child.status)}</span></li>)}</ul></aside>}
 {canSplit(active)&&<section className="admin-split" aria-labelledby="split-title"><h3 id="split-title">{t("每张图片各成一篇")}</h3><p className="subtle">{t("如果这些图片属于不同内容，可拆成独立文章后分别处理。")}</p>{splitTarget?.id===active.id?<div className="split-confirmation" aria-labelledby="split-confirm-title" aria-describedby="split-confirm-details" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();cancelSplit();}}}><h4 id="split-confirm-title">{t("确认拆分这份投稿？")}</h4><p>{splitTarget.title_cn} · {imageCount(splitTarget.originals.length)}</p><ul id="split-confirm-details"><li>{t("每张原稿图片将成为一篇独立文章，并进入等待处理队列。")}</li><li>{t("原投稿保留为私密历史记录，拆分后不能继续处理或发布。")}</li><li>{t("已有英文草稿保留在原投稿，不会带入新文章；本页未保存的修改将丢弃。")}</li><li>{t("每张图片都需单独查看、拟定英文标题、翻译并检查后才能发布。")}</li></ul><div className="split-confirm-actions"><button ref={cancelSplitButton} type="button" className="button secondary small" disabled={busy} onClick={cancelSplit}>{t("取消")}</button><button type="button" className="button primary small" disabled={busy} onClick={confirmSplit}>{splitting&&<LoaderCircle className="spin" size={16}/>} {t("确认拆分为独立文章")}</button></div></div>:<button ref={splitButton} type="button" className="button secondary small" disabled={busy} onClick={beginSplit}>{t("拆分为独立文章")}</button>}</section>}
 {active.status==='pending'&&<div className="alert">{t("请点击「领取下一篇」开始处理。队列按提交时间领取。")}</div>}{active.status==='failed'&&<button className="button secondary small" disabled={busy} onClick={retry}>{t("重新加入处理队列")}</button>}{active.status==='processing'&&!active.lease&&<button className="button secondary small" disabled={busy} onClick={claim}>{t("重新领取过期任务")}</button>}
 <form onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={busy||!processing}><label>{t("英文标题")}<input value={title} onChange={e=>{setTitle(e.target.value);setReviewed(false);}} lang="en" required maxLength={200} placeholder={t("请输入准确的英文标题")}/></label><label>{t("英文正文（选填）")}<textarea value={body} onChange={e=>{setBody(e.target.value);setReviewed(false);}} lang="en" rows={5} maxLength={100000}/></label></fieldset>
 {active.originals.map(original=>{const english=active.images.find(image=>image.position===original.position),preview=outputs[original.position]?.url||(english?'/api/media/'+english.id:null);return <div className="admin-image-pair" key={original.id}><div><h3>{t("第")} {original.position+1} {t("张 · 中文原稿")}</h3><a href={'/api/media/'+original.id+'?download=1'} className="text-link"><Download size={15}/>{t("下载原稿")}</a><a href={'/api/media/'+original.id} target="_blank" rel="noreferrer"><img src={'/api/media/'+original.id} alt={t("第 ")+(original.position+1)+t(" 张中文原稿")} loading="lazy"/></a></div><div><h3>{t("第")} {original.position+1} {t("张 · 英文版本")}</h3>{processing&&<label className="admin-file-label">{t("上传英文图片")}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>selectOutput(original.position,e.target.files[0])}/></label>}{preview?<a href={preview} target="_blank" rel="noreferrer"><img src={preview} alt={t("第 ")+(original.position+1)+t(" 张英文版本")} loading="lazy"/></a>:<p className="admin-image-empty">{t("等待上传英文图片")}</p>}{english&&<a className="text-link" href={'/api/media/'+english.id+'?download=1'}><Download size={15}/>{t("下载英文图片")}</a>}</div></div>;})}
 {processing&&<><label className="admin-review-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)} disabled={busy}/>{t("已检查全部英文文字、画面、图片顺序和版式")}</label><p className="subtle">{t("正在处理时，每 10 分钟自动续期。关闭此页后，请通过处理 API 续期。")}</p><button className="button primary full" disabled={busy||!reviewed||!title.trim()} type="submit">{busy?<LoaderCircle className="spin" size={18}/>:<CheckCircle2 size={18}/>}{t("保存完整英文版本")}</button></>}
 </form>{active.status==='ready'&&<div className="admin-publish"><p className="subtle">{t("管理员可直接发布，无需投稿者再次确认。请先检查完整英文版本。")}</p><button className="button primary full" disabled={busy} onClick={publish}><Globe2 size={18}/>{t("发布英文文章")}</button></div>}</>}
 </section></div>}
 <Link className="text-link back-link" href="/" onNavigate={guardNavigation} aria-disabled={splitting}><ArrowLeft size={15}/>{t("返回公开作品集")}</Link></main></>;
}
